[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
iced_table = { path = "../" }
iced = { git = "https://github.com/project-gauntlet/iced.git", branch = "gauntlet-0.13", features = ["lazy", "winit"] }
